import "./globals.css";
import { Kumbh_Sans } from "next/font/google";
import CartIcon from "./_components/icons/CartIcon";
import Image from "next/image";
import avatar from "../public/images/image-avatar.png";
import Nav from "./_components/Nav";

const Kumbhs = Kumbh_Sans({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Kumbhs.className}>
        <header
          id="Header"
          className="flex justify-between p-6 lg:mx-44 lg:mt-6"
        >
          <Nav />
          <div className="flex space-x-6">
            <CartIcon
              fillColor={
                "fill-current text-DarkGrayishBlue hover:text-Black cursor-pointer self-center"
              }
            />
            <Image
              src={avatar}
              width={40}
              height={20}
              alt="/"
              className="hover:border-2 border-Orange rounded-full w-auto h-auto"
            />
          </div>
        </header>
        <hr className="hidden lg:flex mt-0 mx-44" />
        {children}
      </body>
    </html>
  );
}
